### ISSUE TITLE
一个页面内，由多个答题的任务点事，第一个任务点完成，就跳到下一节了

### ISSUE THREAD

**Issue by JOJOforshaun** [ne-21/Chaoxing_Scripts-#2]
一个页面内，由多个答题的任务点事，第一个任务点完成，就跳到下一节了

**Comment by ne-21** [comment]
这几天我抽空看看，有点忙

在 2020-11-24 20:14:11，JOJOforshaun <notifications@github.com> 写道：


一个页面内，由多个答题的任务点事，第一个任务点完成，就跳到下一节了
