### ISSUE TITLE
判断题好像做不了

### ISSUE THREAD

**Issue by hqu-little-boy** [ne-21/Chaoxing_Scripts-#3]

**Comment by ne-21** [comment]
> _No description provided._

用新版本

**Comment by hqu-little-boy** [comment]
还是不行呀
[http://riyugo.com/i/2020/11/26/e2e897.jpg](url)

**Comment by ne-21** [comment]
> 还是不行呀
> [http://riyugo.com/i/2020/11/26/e2e897.jpg](url)

本人测试无问题，您可以试试谷歌浏览器
