### ISSUE TITLE
关于播放rate无效改进代码如下

### ISSUE THREAD

**Issue by xiaoicx** [ne-21/Chaoxing_Scripts-#4]
#### hookVideo函数下:
```javascript
    player.on("loadstart", function () {
        setting.tip && this.play().catch(Ext.emptyFn);
    });

    player.one(["loadedmetadata", "firstplay"], function () {
	this.playbackRate(
            setting.rate > 16 || setting.rate < 0.0625 ? 1 : setting.rate
        );
        setting.two = setting.rate === "0" && setting.two < 1;
        setting.two &&
        config.plugins.seekBarControl.sendLog(
            this.children_[0],
            "ended",
            Math.floor(this.cache_.duration)
        );
    });
```

**Comment by ne-21** [comment]
> #### hookVideo函数下:
> ```js
>     player.on("loadstart", function () {
>         setting.tip && this.play().catch(Ext.emptyFn);
>     });
> 
>     player.one(["loadedmetadata", "firstplay"], function () {
> 	this.playbackRate(
>             setting.rate > 16 || setting.rate < 0.0625 ? 1 : setting.rate
>         );
>         setting.two = setting.rate === "0" && setting.two < 1;
>         setting.two &&
>         config.plugins.seekBarControl.sendLog(
>             this.children_[0],
>             "ended",
>             Math.floor(this.cache_.duration)
>         );
>     });
> ```

经测试，谷歌浏览器可以视频加速，只不过限制了最大速率为16倍，感谢您的建议，已采纳
